// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAumZgup2W27lfHJSJ852vNIH1Uc94vWCs',
    appId: '1:132915109233:web:7487960523530f289daad0',
    messagingSenderId: '132915109233',
    projectId: 'ecomerce123',
    authDomain: 'ecomerce123.firebaseapp.com',
    storageBucket: 'ecomerce123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ8RRcSyxD_i996Eh8GTJBFOmyerNdskI',
    appId: '1:132915109233:android:eea477c854b492519daad0',
    messagingSenderId: '132915109233',
    projectId: 'ecomerce123',
    storageBucket: 'ecomerce123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvTHLomUujgpgZaoXEdit6zl2PSPe55w',
    appId: '1:132915109233:ios:f62d99912e9dc3649daad0',
    messagingSenderId: '132915109233',
    projectId: 'ecomerce123',
    storageBucket: 'ecomerce123.appspot.com',
    iosClientId: '132915109233-h4va58l7nr6ieg1rfq0mgs6690sdgp5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomm',
  );
}
